CREATE TABLE "CNF_RJ_STAGING"(
 "ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_ID" UNIQUE USING 0,
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "EMPLOYEEID" CHAR(5),
 "CREATEDON" DATETIME,
 "CREATEDONEMPLOYEEID" CHAR(5),
 "MODIFIEDON" DATETIME,
 "MODIFIEDONEMPLOYEEID" CHAR(5),
 "PROCESSEDSTATUSTOGSMTABLES" CHAR(20),
 "PROCESSEDDATETOGSMTABLES" DATETIME,
 "STATUS" CHAR(20),
 "COCODE" CHAR(3) NOT NULL,
 "UID" INTEGER );
