CREATE TABLE "GAB_5874_FS_NOTES" (
 "ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_ID" UNIQUE USING 0,
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "FSNOTES" LONGVARCHAR,
 "SEQ" CHAR(3),
 "CREATEDON" DATETIME,
 "CREATEDONEMPLOYEEID" CHAR(5) );