CREATE TABLE GAB_5874_FS_SIG(
 "ID" IDENTITY DEFAULT 0 NOT NULL,
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SIGNATURE" LONGVARBINARY,
 "SIGNAME" CHAR(30),
 "CREATEDON" DATETIME,
 "CREATEDONEMPLOYEEID" CHAR(5),
 "STATUS" CHAR(20));

