CREATE TABLE "GAB_5874_FS_INFO"
 (EMPLOYEEID CHAR(5),
 EMPLOYEENAME CHAR(30),
 COMPANYCODE CHAR(3),
 BIN CHAR(6),
 LOC CHAR(2),
 SUPERVISORID CHAR(5),
 SUPERVISORNAME CHAR(30),
 MANUAL BIT DEFAULT '0' NOT NULL,
 CREW BIT DEFAULT '0' NOT NULL,
 CREWLEADID CHAR(5),
 CREWLEADNAME CHAR(30) );

CREATE UNIQUE NOT MODIFIABLE INDEX GAB_5874_FS_INFOK00 IN DICTIONARY ON GAB_5874_FS_INFO
(EMPLOYEEID ASC);