Create Table GSM_LINE_FIELDS(
LFID IDENTITY DEFAULT '0' CONSTRAINT "UK_LFID" UNIQUE USING 0,
LID INT NOT NULL REFERENCES GSM_LINE(LID),
HID INT NOT NULL REFERENCES GSM_HEADER(HID),
LFIELDNAME CHAR(50),
LFIELDVAL CHAR(50));